# ASP.NET Core (.NET Framework) 
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- none

jobs:
- job: AutoComplete_Jira_2019
  timeoutInMinutes: 0
  pool:
    name: "Desktop-xaml-vmss"

  steps:
  - task: ScreenResolutionUtility@1
    inputs:
        displaySettings: 'specific'
        width: '1366'
        height: '768'

  - task: CmdLine@1
    inputs:
        filename: 'UIAutomationConsole.exe'
        workingFolder: '$(Build.SourcesDirectory)\net6.0\'
        arguments: 'https://svn.syncfusion.com/svn/studio/Source/Testing/Automation/TestCases_Automation/TestStudioAutomation/Tools_WPF/AutoComplete_Jira_2019
                    development 
                    syncfusion-licensing,null;shared-wpf,null;tools-wpf,null;sfshared-xaml,null;edit-wpf,null;propertygrid-wpf,null;sfbusyindicator-xaml,null;sfinput-xaml,null;sfradialmenu-xaml,null;sfrichtextribbon-wpf,null;sfskinmanager-wpf,null;sftreenavigator-xaml,null;themes-wpf,null'
    
  - task: PublishBuildArtifacts@1
    inputs:
        pathtoPublish: 'D:\AutomationReports\'
        ArtifactName: AutoComplete_Jira_2019

- job: ButtonAdv_Jira_2019
  timeoutInMinutes: 0
  pool:
    name: "Desktop-xaml-vmss"

  steps:
  - task: ScreenResolutionUtility@1
    inputs:
        displaySettings: 'specific'
        width: '1366'
        height: '768'

  - task: CmdLine@1
    inputs:
        filename: 'UIAutomationConsole.exe'
        workingFolder: '$(Build.SourcesDirectory)\net6.0\'
        arguments: 'https://svn.syncfusion.com/svn/studio/Source/Testing/Automation/TestCases_Automation/TestStudioAutomation/Tools_WPF/ButtonAdv_Jira_2019 
                    development 
                    syncfusion-licensing,null;shared-wpf,null;tools-wpf,null;sfshared-xaml,null;edit-wpf,null;propertygrid-wpf,null;sfbusyindicator-xaml,null;sfinput-xaml,null;sfradialmenu-xaml,null;sfrichtextribbon-wpf,null;sfskinmanager-wpf,null;sftreenavigator-xaml,null;themes-wpf,null'
    
  - task: PublishBuildArtifacts@1
    inputs:
        pathtoPublish: 'D:\AutomationReports\'
        ArtifactName: ButtonAdv_Jira_2019
